cors:
  origin: http://localhost:300
  # by default is GET, HEAD, POST
  # "*" allows all methods
  allowed-method: "*"

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
#  pattern:
#    console: "%{MM-dd HH:mm:ss} - %logger{36} - %msg%n"